### PR TITLE
Stripped query string redirect integrity

### PR DESCRIPTION
**Pull request by fiasco**
Make sure unique values of X-Acquia-Stripped-Query are stored in different cache variations in Acquia Varnish.

### CODE REVIEW

**Comment by ghazlewood** [comment]
@fiasco Thanks for the excellent suggestion here, I wholeheartedly agree that this could save us from inadvertently save us from polluting caches.  Would the logic you have proposed be better inside the conditionals as it should only be applied to requests we are handling (301/302s), or did you see this as having a benefit for all requests?

**Comment by benjast** [comment]
@fiasco @ghazlewood I suppose adding this additional code would negate the need for installing the `acquia_geoip_vary_by_country` module. Is that what you may be thinking?

**Comment by ghazlewood** [comment]
This has been fixed in #9 by rsaddington

**Comment by fiasco** [comment]
> Would the logic you have proposed be better inside the conditionals

No Vary values need to be present on all variations of a given URL regardless of whether the logic applies or not. Otherwise you may still get an incorrect cache hit.

**Pull request closed without merging**
